remote_theme: artemsheludko/monday

title: Viktor Arsovski
description: > # this means to ignore newlines until "baseurl:"
  Viktor Arsovski Senior Android Software engineer.
  Enthusiasm in Java, Kotlin, Node.js.
  Evolutionary psychology, football (soccer), snowboarding

# Profile information
name: Viktor Arsovski
tagline: Senior Software Engineer
about-description: 
pic: 79.png

# Contact links
email: contact@viktorarsovski.xyz
website: viktorarsovski.xyz
linkedin: varsovski
github: ViksaaSkool
twitter: '@ViksaaSkool'
skype: viktor__arsovski
medium: '@viksaaskool'
wordpress: viksaaskool
stackoverflow: users/1036120/viksaaskool
reddit: viksaaskool
