remote_theme: artemsheludko/monday


# Profile information
name: Viktor Arsovski
tagline: Software Engineer
about-description: gfdhsdfhdghd dfgd h gdgd hd # Add Discription
pic: 79.png  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: contact@viktorarsovski.xyz # Add your Email address
phone: 044 825 5523 # Add your Phone number
website: viktorarsovski.xyz # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: ViksaaSkool # Add your Github handle
twitter: '@ViksaaSkool' # Add your Twitter handle
skype: viktor__arsovski
medium: '@viksaaskool'
wordpress blog: viksaaskool.wordpress.com
reddit: viksaaskool
